import EventEmitter from 'events';

export enum AppEvents {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_INFO_CHANGE_REQUESTED = 'USER_INFO_CHANGE_REQUESTED',
  
  PROPERTY_SUBMITTED = 'PROPERTY_SUBMITTED',
  PROPERTY_APPROVED = 'PROPERTY_APPROVED',
  PROPERTY_REJECTED = 'PROPERTY_REJECTED',
  PROPERTY_EXPIRED = 'PROPERTY_EXPIRED',
  PROPERTY_RENEWED = 'PROPERTY_RENEWED',
  PROPERTY_VIEWED = 'PROPERTY_VIEWED',
  
  ENQUIRY_CREATED = 'ENQUIRY_CREATED',
  REQUIREMENT_SUBMITTED = 'REQUIREMENT_SUBMITTED',
  
  REVIEW_SUBMITTED = 'REVIEW_SUBMITTED',
  REVIEW_MODERATED = 'REVIEW_MODERATED',
  
  VERIFICATION_REQUESTED = 'VERIFICATION_REQUESTED',
  VERIFICATION_UPDATED = 'VERIFICATION_UPDATED',
  
  ANALYTICS_EVENT = 'ANALYTICS_EVENT',
}

class EventBus extends EventEmitter {
  constructor() {
    super();
    this.setMaxListeners(50);
  }

  emitEvent(event: AppEvents, payload: any) {
    this.emit(event, payload);
  }
}

export const eventBus = new EventBus();
